import "./globals.css";
import { Ubuntu } from "next/font/google";
import styles from "./page.module.css";
export const metadata = {
  title: "Just Another Todo App",
  description: "Generated by create next app",
};
// A different font... because why not
const ubuntu = Ubuntu({ subsets: ["latin"], weight: "300" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body> 
        <main className={`${styles.main} ${ubuntu.className}`}>{children}
      </main>
      </body>
    </html>
  );
}
